export const RELATION_MAP_FOR_SUBCATEGORY = "RELATION_MAP_FOR_SUBCATEGORY";
export const RELATION_MAP_FOR_CATEGORY = "RELATION_MAP_FOR_CATEGORY";

export const UNSELECTED_CATEGORY = "Choose Category";
export const UNSELECTED_SUBCATEGORY = "Choose Subcategory";
