export const CELL_TYPE_INPUT = "CELL_TYPE_INPUT";
export const CELL_TYPE_DROPDOWN = "CELL_TYPE_DROPDOWN";
export const CELL_TYPE_DEFAULT = "CELL_TYPE_DEFAULT";
export const CELL_TYPE_CHECKBOX = "CELL_TYPE_CHECKBOX";
export const CELL_TYPE_HEADER = "CELL_TYPE_HEADER";
export const CELL_TYPE_ACTION = "CELL_TYPE_ACTION";

export const FIELD_TYPE_PRODUCT = 'Product';
export const FIELD_TYPE_SUBCATEGORY = 'Subcategory';
export const FIELD_TYPE_CATEGORY = 'Category';

export const ROW_TYPE_HEADING = "ROW_TYPE_HEADING";
export const ROW_TYPE_DEFAULT = "ROW_TYPE_DEFAULT";
export const ROW_TYPE_ADD_NEW = "ROW_TYPE_ADD_NEW";

export const ROW_ADDER_STATE_SHOW = "ROW_ADDER_STATE_SHOW";
export const ROW_ADDER_STATE_DISABLED = "ROW_ADDER_STATE_DISABLED";
